version: '3'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - '8080:8080'
        depends_on:
            - database
        environment:
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_URL: database:5432
    database:
        image: 'postgres:13-alpine'
        restart: always
        container_name: db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '5432:5432'
