spring:
    datasource:
        url: jdbc:postgresql://${DB_URL}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        hibernate.ddl-auto: create-drop
        generate-ddl: true
        show-sql: true
