spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/typing_speed_test
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: password # encoding it would be a better practice

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true